# Site settings
title: Sweet Farm
email: support@sweetfarm.org
description: >
  An Animal Sanctuary in Half Moon Bay
baseurl: ""
url: "https://www.sweetfarm.org"

# Social Settings
facebook_username: SweetFarmCA
twitter_username: TheSweetFarm
instagram_username: TheSweetFarm
github_username:  sweetfarm

# Github Settings 
lsi: false
safe: true
incremental: false

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass

#gems:
  
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
