# Site settings
title: Sweet Farm
description: >
  An Animal Sanctuary in Half Moon Bay
baseurl: ""
url: "https://www.sweetfarm.org"

# Site defaults
permalink: /news/:year/:month/:day/:title/

defaults:
  - 
    scope:
      path: ""
      type: residents
    values:
      layout: resident
      css: /css/resident.css
  -
    scope:
      path: ""
      type: posts
    values:
      layout: posts
      css: /css/simple.css

# Custom Collections
collections:
  residents:
    output: true
    permalink: /:collection/:name/index.html

# Social Settings
facebook: SweetFarmCA
twitter: TheSweetFarm
instagram: TheSweetFarm

# Contact Settings
email: info@sweetfarm.org
phone: '+1 (206) 618-0406'
address_1: 131 Tunitas Creek Road
address_2: Half Moon Bay, CA 94109

# Github Settings 
lsi: false
safe: true
incremental: false

# Build settings
sass:
  sass_dir: _sass
  
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
